development: &common
  adapter: postgresql
  encoding: unicode
  database: feed-challenge-rails_development
  username: rails
  password: password
  host: localhost


production:
  <<: *common
  database: feed-challenge-rails_production
